### ISSUE TITLE
Tags linked in post can point to non-existing sites

### ISSUE THREAD

**Issue by digitalcraftsman** [nanxiaobei/hugo-paper#1]
Hi @nanxiaobei,

in the demo for your theme I noticed that the tags at the [bottom of a blog post](https://themes.gohugo.io/theme/hugo-paper/post/hugoisforlovers/) are relative to the root of a url. Since the demos are hosted in a subdirectory this means that the links are relative to `www.themes.gohugo.io`. Therefore you link `www.themes.gohugo.io/tags/TAG` instead of `themes.gohugo.io/theme/hugo-paper/tags/TAG`.

When linking pages and assets also [make sure that your partial link doesn't start with a /](https://github.com/nanxiaobei/hugo-paper/blob/master/layouts/_default/single.html#L16). Otherwise those functions will make it relative to the root (by design).

**Comment by nanxiaobei** [comment]
Hi, I've fixed the absolute url issue, hope you check it again~

**Comment by digitalcraftsman** [comment]
It's fixed. Thanks :+1: 

I'll update theme theme site a moment (including your theme's demo).
