### ISSUE TITLE
日期不显示的问题

### ISSUE THREAD

**Issue by realzhangm** [nanxiaobei/hugo-paper#105]
![image](https://user-images.githubusercontent.com/6488835/160949499-f5d9da91-3c99-45ec-b9bb-28a0042d74ff.png)

日期显示 date_medium

**Comment by nanxiaobei** [comment]
看下 `hugo` 版本是否 `>=v0.87.0`
https://gohugo.io/functions/dateformat/#datetime-formatting-layouts
