### ISSUE TITLE
`` in <code> tag render effect is missing

### ISSUE THREAD

**Issue by h0wardch3ng** [nanxiaobei/hugo-paper#122]
<img width="755" alt="Screen Shot 2022-08-12 at 11 15 20" src="https://user-images.githubusercontent.com/2175497/184278650-249512f9-5ed3-4e18-8791-ee8ca810cd10.png">

https://hugo-paper.vercel.app/post/markdown-syntax/

**Comment by nanxiaobei** [comment]
what's the expected render effect?

**Comment by h0wardch3ng** [comment]
`Test測試123@#$`


<img width="265" alt="image" src="https://user-images.githubusercontent.com/2175497/184290860-7338faea-70d9-4a4d-8a17-1a01d9ddd7e8.png">

<img width="305" alt="image" src="https://user-images.githubusercontent.com/2175497/184290932-ad07cda9-e0d6-4c85-9074-3e2a8d6086af.png">

<img width="288" alt="image" src="https://user-images.githubusercontent.com/2175497/184290979-6f80444d-d400-4cc6-8bd9-311bf34bdd9d.png">

Light and dark theme.

**Comment by nanxiaobei** [comment]
Article style tile uses this: https://tailwindcss.com/docs/typography-plugin , so there is a certain change from the previous style. 
At present, in principle, do not consider covering some special cases. If many people need it, may consider modifying it.

**Comment by realandrew** [comment]
This actually changed from previous versions. Paper 5.1 did display this correctly. I just updated to Paper 6.2 which does not. Unless this was a purposeful change, this is a regression.

**Comment by 0ne1astk155** [comment]
@realandrew You can comment this issue again. https://github.com/tailwindlabs/tailwindcss-typography/issues/279
