### ISSUE TITLE
`pre` element styling

### ISSUE THREAD

**Issue by mangkoran** [nanxiaobei/hugo-paper#127]
First of all, thank you for your hard work to create this template!

I have a question regarding `pre` styling. How can I change the `style` tag of `pre` element here? I would like to change it's background color. However, I couldn't find any declaration of it in `assets/` directory.

![image](https://user-images.githubusercontent.com/57625126/193200583-5e46af22-b9a2-443b-a9d6-784c7158fbc4.png)

**Comment by mangkoran** [comment]
This is what I actually want. This is done by 4 spaces indent.

However, I would like to still use the triple backtick code block so that I could declare the code language and get syntax highlighting.

![image](https://user-images.githubusercontent.com/57625126/193231077-b03d2ade-38fc-4832-93fa-bd678959a76e.png)

**Comment by mangkoran** [comment]
Turns out the `style` tag is inserted by the highlighter js (idk what package is used). Sorry for disturbing 😅

**Comment by nanxiaobei** [comment]
It's [highlight.js](https://highlightjs.org/) to styling code blocks, you can disable it by `disableHLJS = true`.
