### ISSUE TITLE
Dark mode flickers when page loads

### ISSUE THREAD

**Issue by khoi** [nanxiaobei/hugo-paper#128]
❤️ Great theme, I have 1 small problem. When the dark mode is selected, u navigate away to a new page, it flickers from light -> dark mode 

For instance:  
- https://www.khoi.io/ - Go here and turn on dark mode
- https://www.khoi.io/post/sorting/ - This page is kinda heavy, you'll see the white flickers for a brief moment

**Comment by nanxiaobei** [comment]
Yes, the dark theme is set by script of detecting the local storage. so render - detect - set will have a little time gap.
I will try to figure out if there is a better way later.
