### ISSUE TITLE
Darkmode block quote

### ISSUE THREAD

**Issue by khoi** [nanxiaobei/hugo-paper#129]
In dark mode block quote should probably have a whiteline or something

<img width="972" alt="CleanShot 2022-10-27 at 23 24 06@2x" src="https://user-images.githubusercontent.com/6994441/198345778-600b454e-b655-43c8-b23a-192630ee95f8.png">

![CleanShot 2022-10-27 at 23 24 23@2x](https://user-images.githubusercontent.com/6994441/198345855-3f15903c-b837-474f-9836-f3bcbb2c531b.png)

**Comment by nanxiaobei** [comment]
thanks feedback, will fix it.

**Comment by nanxiaobei** [comment]
Fixed in `6.4.0`
