### ISSUE TITLE
本地显示正常，但是github不能显示post

### ISSUE THREAD

**Issue by ilongshan** [nanxiaobei/hugo-paper#130]
我的本地显示正常，但是github上不能显示post：
https://github.com/codeclabs-cn/codeclabs-cn.github.io
baseUrl已经设置了，posts目录也改成post了，已经添加了content/post/_index.md文件。
请问该怎么修改呢？

**Comment by nanxiaobei** [comment]
可参考此处目录结构：
https://github.com/nanxiaobei/hugo-paper/tree/main/exampleSite
