### ISSUE TITLE
Add Mastodon Support

### ISSUE THREAD

**Issue by WillGreen** [nanxiaobei/hugo-paper#132]
Hello, I've recently moved to Mastodon as my main social platform and would like Hugo Paper to support Mastodon in `config.toml` in a similar way to Twitter. An example of another Hugo theme with Mastodon support is [Kiss](https://github.com/ribice/kiss).

Thank you for creating and maintaining this excellent theme.

**Comment by nanxiaobei** [comment]
Thanks for the suggestion, added Mastodon in `6.5`.
