### ISSUE TITLE
请问能否设置gravatar的代理？

### ISSUE THREAD

**Issue by yazinnnn** [nanxiaobei/hugo-paper#134]
avatar渲染后的地址是官方地址，gfw内访问困难，请问能否设置gravatar的cdn代理？比如https://cdn.v2ex.com/gravatar/

**Comment by nanxiaobei** [comment]
好的，将提供一个设置 gravatar 代理的配置项

**Comment by yazinnnn** [comment]
> 好的，将提供一个设置 gravatar 代理的配置项

感谢

**Comment by nanxiaobei** [comment]
`6.6` 添加了 `gravatarCdn` 选项。
