### ISSUE TITLE
multi-author support

### ISSUE THREAD

**Issue by rchaganti** [nanxiaobei/hugo-paper#137]
I love how simple this theme is. I am looking at setting this theme up for a team of people and would like to add multi-author support. Essentially, make the author name clickable in the post header, and have an author page with a bio, profile pic, and social links. Is this something I can implement with some customizations? I am still learning how Hugo themes are built.

I would appreciate any help/suggestions.

**Comment by nanxiaobei** [comment]
Sorry but I don't have to much time to add additional functions now, and PR welcome.

**Comment by rchaganti** [comment]
@nanxiaobei totally understand. Can you point me to any docs that I can use to try this?
