### ISSUE TITLE
GraphComment and Disqus are also active in About and Contact pages

### ISSUE THREAD

**Issue by doganmehmet** [nanxiaobei/hugo-paper#139]
First of all, thanks very much for creating this super cute theme and making available to everyone.  In particularly thank you for making it up to date - this is very useful (e.g., just putting comment IDs to make commenting available on the site) for non-technical people like me.

I activated GraphComment, via setting graphCommentId: myID in config file, on my website. It perfectly works but also active in About and Contact pages. Is there any way to block commenting (either GraphComment or Disqus) from those two (or any other specific) pages. 

Thank you in advance.

**Comment by nanxiaobei** [comment]
You can add `comments = false` to the front matter of About and Contact pages to disable the comments.
https://github.com/nanxiaobei/hugo-paper/blob/main/layouts/_default/single.html#L59

**Comment by doganmehmet** [comment]
Thank you very much. Works like a charm.
