### ISSUE TITLE
vercel 部署失败，直接下载拷贝到 themes 下

### ISSUE THREAD

**Issue by liuyangzuo** [nanxiaobei/hugo-paper#140]
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/8985760/215955656-74bb6e62-8196-4bdd-909f-541ebfb46bfc.png">

**Comment by nanxiaobei** [comment]
可能是服务不稳定 或其他问题？
Demo https://hugo-paper.vercel.app/ 也是在 Vercel 部署的，可以成功部署，刚又 redeploy 试了一下。
