### ISSUE TITLE
after Deploying Netlify, no CSS no image shown, using this theme

### ISSUE THREAD

**Issue by Hurricane-k** [nanxiaobei/hugo-paper#143]
When I check my website locally, everything works well, including words, images, CSS. But after using `hugo` to generate `public\` file fold, and git them to my GitHub repository and deploy the repository by Netlify, and set `HUGO_VERSION` as `0.110.0` coz that's the hugo version I am using, but there's no CSS, no image shown, and hyperlink doesn't work well

**Comment by nanxiaobei** [comment]
Sorry but I think this should not be a theme issue, but a deployment issue.
