### ISSUE TITLE
404 after deploying Netlify

### ISSUE THREAD

**Issue by Hurricane-k** [nanxiaobei/hugo-paper#144]
After I checked out my local rendered website, I git them to GitHub and then deploy them using Netlify, but only 404 page.<br>
That is [my website](https://carrybio.netlify.app/)
That is [the connected respority](https://github.com/Hurricane-k/Carry-Bio)
Next is the screenshot about my local well-rendered website
![locally well-rendered homepage screenshot](https://user-images.githubusercontent.com/56281608/216990568-4068b192-c7c1-4dc9-bca7-7c7674b87f6b.png)

**Comment by Hurricane-k** [comment]
there is a little bit difference on adding something in menu bar. I prefer `content/about/index.md` to `content/about.md` coz I wanna add image in the same directory. is that the root of problem? should i need to add `homepage/` under `content`?

**Comment by nanxiaobei** [comment]
Sorry but I think this is a deploy issue, not be a theme issue.
I can not help because I have not tried to deployed to Netlify before.
