### ISSUE TITLE
Gist CSS formatting

### ISSUE THREAD

**Issue by gentleadam** [nanxiaobei/hugo-paper#150]
When adding a gist using the hugo shortcode (https://gohugo.io/content-management/shortcodes/#gist) the gist contains lots of lines which aren't displayed on githubs version.

paper version
![image](https://user-images.githubusercontent.com/21122180/218305928-4c63c565-86ec-43f6-b455-7efe3b157659.png)

Github version
![image](https://user-images.githubusercontent.com/21122180/218305973-02b56712-fde3-4cc7-b36e-5ecbed1229a4.png)

I believe this is related to this CSS rule in main.css file

```
/*
1. Prevent padding and border from affecting element width. (https://github.com/mozdevs/cssremedy/issues/4)
2. Allow adding a border to an element by just adding a border-width. (https://github.com/tailwindcss/tailwindcss/pull/116)
*/

*,
::before,
::after {
  box-sizing: border-box;
  /* 1 */
  border-width: 0;
  /* 2 */
  border-style: solid;
  /* 2 */
  border-color: #e5e7eb;
  /* 2 */
}
```
Specifically the `border-style: solid;`

Also as a side note, do you have any documentation on how to theme things for the dark mode? I would like to add a dark version of the gist if possible.

**Comment by nanxiaobei** [comment]
1. can you provide a demo page of the "border" effect?
2. "ow to theme things for the dark mode", it's just CSS, no simple documentation way to do it.

**Comment by gentleadam** [comment]
> 1. can you provide a demo page of the "border" effect?
> 2. "how to theme things for the dark mode", it's just CSS, no simple documentation way to do it.

1 - I just create a new blank markdown file and add the shortcode for the gist as per the hugo documentation - `{{< gist spf13 7896402 >}}`

2 - Do you know where specifically css for that is controlled and should be added?

**Comment by nanxiaobei** [comment]
1. ok, I'll take a look
2. this theme uses Tailwind CSS, so you can only overwrite the CSS(in [custom.css](https://github.com/nanxiaobei/hugo-paper/blob/main/assets/custom.css)), can not "change" it.

**Comment by gentleadam** [comment]
Thanks, in order to use custom.css I assume we need to fork the repo?

**Comment by nanxiaobei** [comment]
edit on your own downloaded file of paper theme is fine
