### ISSUE TITLE
How to change the the background color when it's dark mode.

### ISSUE THREAD

**Issue by Jin-K-Yang** [nanxiaobei/hugo-paper#152]
Hello, I saw this amazing template in Hugo, but there is one thing I want to adjust. I want to change the color of background when user turns into darkmode. I think the currently black is too dark, I have been trying modify app.css and main.css but it doesn't work, which line should I modify to adjust the dark mode background color? thank you very much , love this template so much!

**Comment by nanxiaobei** [comment]
the source code is this line: https://github.com/nanxiaobei/hugo-paper/blob/main/assets/app.css#L27

you need to run `npm run dev` first, and then change `@apply dark:bg-black` to `@apply dark:bg-black/80`(which means `rgba(0, 0, 0, 80%)`).

**Comment by Jin-K-Yang** [comment]
Hey, it didn't work for me, but I saw this line could help me change to color: https://github.com/nanxiaobei/hugo-paper/blob/6c2ed14a7e970c8899150407c2be4a475e1eb5f2/assets/main.css#L444, thanks~

**Comment by nanxiaobei** [comment]
yes main.css is the file after build. the source file is app.css.
