### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by igorkulman** [nanxiaobei/hugo-paper#153]
Checking https://pagespeed.web.dev/report?url=https%3A%2F%2Fhugo-paper.vercel.app%2F I think there are a few easy improvements that can be done and I am experimenting with thinking about upgrading to this theme from a very old version of Paper

- add alt to the avatar, make if for example the site name
- add text to the social link, make it just {{ . }} and add CSS rule to hide the text
- add text to the links in list, make it {{ .Title }} and add CSS rule to hide the text

This gets the accessibility score from 85 to 100.

**Comment by nanxiaobei** [comment]
thanks for your advice, will update it.
