### ISSUE TITLE
Tags and Category Pages Have No Content

### ISSUE THREAD

**Issue by WillGreen** [nanxiaobei/hugo-paper#156]
Hello,

Paper creates list pages for tags and categories, but they aren't populated.

The example site has this issue, for example:

* shortcode tag page has content: https://hugo-paper.vercel.app/tags/shortcodes
* tags page doesn't list tags: https://hugo-paper.vercel.app/tags/ 
* themes category page has content: https://hugo-paper.vercel.app/categories/themes
* categories page doesn't list categories: https://hugo-paper.vercel.app/categories

Can these pages be populated so visitors can browse tags and categories?

Thank you for all your hard work in creating and maintaining this theme.

**Comment by nanxiaobei** [comment]
Thank you for your feedback, but this is intentional.
This is a theme based on simplicity, so no detailed tags and categories page will be added at present.
If there is PR or strong demand, it may be considered in the future.

**Comment by WillGreen** [comment]
I understand. I thought it might be deliberate, but decided it could be a bug because empty tag and category pages are created. I can add them to my .gitignore file so they don't get added to my blog. Thanks.

**Comment by Jin-K-Yang** [comment]
If there is categories function that would be nice, I think with more and more posts, this feature will be more and more necessary.
