### ISSUE TITLE
Header title link doesn't match footer title link

### ISSUE THREAD

**Issue by hienvl125** [nanxiaobei/hugo-paper#159]
Hi @nanxiaobei 
When deployed a hugo project to github pages and configured **baseURL**
```
baseURL = 'https://my-git-username.github.io/my-git-repo/'
```

The title link of header and title link of footer are different
<img width="619" alt="image" src="https://user-images.githubusercontent.com/40386066/222957688-5f726224-204b-4ace-888f-61a91de785e6.png">

I solved this by changing title link of header from 
```
href="{{ `/` | absURL }}"
->
href="{{ `` | absURL }}"
```
but I saw this PR changed title link of header https://github.com/nanxiaobei/hugo-paper/pull/154/files
Do you have any suggestions for my case?

**Comment by nanxiaobei** [comment]
This is a edge case based on different usages.
I think `href="{{ `` | absURL }}"` is more in line with expectations, you can keep your modification to use, and maybe hugo-paper will update to `href="{{ `` | absURL }}"` again.
