### ISSUE TITLE
Error: add site dependencies

### ISSUE THREAD

**Issue by houzeyu2683** [nanxiaobei/hugo-paper#161]
Error: add site dependencies: load resources: loading templates: "HUGO_PROJECT/themes/paper/layouts/partials/head.html:34:1": parse failed: template: partials/head.html:34: unclosed action

```
hugo version
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z
```

```
go version 
go1.13.8 linux/amd64
```

**Comment by nanxiaobei** [comment]
updated, please git pull the theme again.
