### ISSUE TITLE
Feature request: Add Latex renderer

### ISSUE THREAD

**Issue by Avimitin** [nanxiaobei/hugo-paper#164]
It will be convenient if this theme can support a Latex renderer. There are many JavaScript API had already implemented it, like katex (https://katex.org/). 

I've tried to import katex into hugo-paper, see https://github.com/Avimitin/hugo-paper/commit/0311c2df32df113b721c8aca01906220b5bf1836. It is working, but I have zero experiment on developing a hugo theme, so I don't know if I do it in the right way or not. You can take a look on that commit. And if my implementation is correct, I would like to create a new PR for this feature.

**Comment by Avimitin** [comment]
Update: It seems putting the script loader in single page is not necessary, so I moved it into the head.html. See https://github.com/Avimitin/hugo-paper/commit/575af47eccc12b67961d4e845bec0f973666942d. This might help loading the renderer earlier.

**Comment by nanxiaobei** [comment]
Added on `6.11.0`.
