### ISSUE TITLE
tag links are incorrect when uglyURLs = true

### ISSUE THREAD

**Issue by ksqsf** [nanxiaobei/hugo-paper#168]
When uglyURLs = true, href should contain ".html" here

https://github.com/nanxiaobei/hugo-paper/blob/main/layouts/_default/single.html#L30

**Comment by nanxiaobei** [comment]
You can edit the templates yourself cause Hugo does not provide an elegant way to do that.

https://github.com/gohugoio/hugo/issues/1989#issuecomment-212367257
