### ISSUE TITLE
baseURL跳转错误

### ISSUE THREAD

**Issue by dairongpeng** [nanxiaobei/hugo-paper#177]
如题，在使用过程中，指定baseURL为`http://localhost:1313/blog/`，点击标题Title的超链接，跳转到了`http://localhost:1313`, 而不是baseURL的地址。导致404空白页的出现。

我应该如何配置，来控制`Title`的超链接，跳转到baseURL，或指定的地址？

**Comment by nanxiaobei** [comment]
已修复，可重新 clone 主体尝试。
