### ISSUE TITLE
生成的HTML文件，代码块模块存在不对齐问题

### ISSUE THREAD

**Issue by dairongpeng** [nanxiaobei/hugo-paper#178]
博客文本格式大致如下：

# 一级标题
我是一级标题下的正文。

演示下代码块流程：
```shell
cd ~
echo "hello world"
```

## 二级标题
二级标题下的正文

插入一张图片：
![](../imgs/test.png)

上面的Markdown，生成html后，`标题，正文，引入`的图片可以对齐；`代码块`不能对齐，造成的效果可能是由于`标题，正文，引入的图片`统一进行了缩进，也可能是`代码块`布局的问题。

具体的Case:

![image](https://github.com/nanxiaobei/hugo-paper/assets/28700908/b04d5999-5994-41e6-923c-5e845fb74936)

**Comment by nanxiaobei** [comment]
这个 ... 代码块突出效果，是故意设计成这样的。

**Comment by dairongpeng** [comment]
正如我当前issues里面的提问，github的markdown渲染是，代码块和标题以及正文是对齐的，这样不会显得很突兀。这个好修复么，或者我应该修改哪里，可以改成左对齐的呢。我使用的是子模块，也比较方便修改源代码。非常感谢！

**Comment by dairongpeng** [comment]
> 这个 ... 代码块突出效果，是故意设计成这样的。

如果只改具体的博客对应的html文件，这个作用返回比较小，每篇博客可能都需要处理，而且技术博客这种代码块还挺多的。所以期望可以从生成器框架的的位置来修复，期待可以提供一个办法，谢啦

**Comment by nanxiaobei** [comment]
https://github.com/nanxiaobei/hugo-paper/blob/0fdcdf371b26ebe74fd24f9549261dc2f2825581/assets/main.css#L1627-L1628

把 `article pre { }` 下的 `margin-left` `margin-right` 这两行去掉。

**Comment by dairongpeng** [comment]
解决了，感谢！
