### ISSUE TITLE
Feature request: Use local avatar image

### ISSUE THREAD

**Issue by igorkulman** [nanxiaobei/hugo-paper#181]
It would be nice to have the ability to easily use a local avatar image instead of using the Gravatar provided image, especially if you to not want your website to do any request to 3rd party sites.

**Comment by nanxiaobei** [comment]
Actually, you can directly pass in a URL to `avatar`

**Comment by calalloo** [comment]
> Actually, you can directly pass in a URL to `avatar`

How? I added `avatar = "images/avatar.webp"` under `params and still the gravatar URL shows up.
