### ISSUE TITLE
How to override font-sizes

### ISSUE THREAD

**Issue by papertigers** [nanxiaobei/hugo-paper#183]
Is there an easy way to override font sizes? 
I was able to do something like `article { font-size: 1em }` and that seems to work.
The font I would really like to adjust would be the code blocks.  I can edit it directly in the `.prose` section of main.css but that seems a little hacky.

**Comment by nanxiaobei** [comment]
You can set `font-size` to `html` tag to override all.
Like `font-size: 12px` or something.
