### ISSUE TITLE
大佬，生成报错了

### ISSUE THREAD

**Issue by qsthhm** [nanxiaobei/hugo-paper#187]
add site dependencies: load resources: loading templates: "/www/wwwroot/***/themes/hugo-paper/layouts/partials/head.html:46:1": parse failed: template: partials/head.html:46: unexpected unclosed action in command

**Comment by nanxiaobei** [comment]
无法复现 ...

**Comment by qsthhm** [comment]
服务器：新装的debian 11系统，装了  mdserver-web 面板(但感觉影响不大)
安装方式：apt install hugo
主题安装：git clone https://github.com/nanxiaobei/hugo-paper.git
config.toml:
baseURL = "***"
languageCode = "zh-cn"
title = "***"
theme = 'hugo-paper'
[params]
  description = "Design Desire Explore"
  comments = true

然后用hugo 命令生成就报错了：
Error: add site dependencies: load resources: loading templates: "/www/wwwroot/***/themes/hugo-paper/layouts/partials/head.html:46:1": parse failed: template: partials/head.html:46: unexpected unclosed action in command

测试了 paperMod正常

**Comment by nanxiaobei** [comment]
看下是不是 hugo 版本的问题
https://discourse.gohugo.io/t/error-unexpected-unclosed-action-in-command/36848

**Comment by qsthhm** [comment]
感谢大佬，确定就是版本问题。
