### ISSUE TITLE
移动端优化：引用和代码块

### ISSUE THREAD

**Issue by peanut996** [nanxiaobei/hugo-paper#194]
移动端浏览器展示引用的黑条以及代码块会直接贴着屏幕两边

第一时间无法快速注意到引用

是否考虑添加一下margin呢

![image](https://github.com/nanxiaobei/hugo-paper/assets/32303768/deb46aac-7415-4f6a-a79d-d80da37e1fd6)
![image](https://github.com/nanxiaobei/hugo-paper/assets/32303768/10f45a47-5205-4648-bcf5-6f9049a3c233)

**Comment by nanxiaobei** [comment]
目前是这么设计的，暂无更新计划
