### ISSUE TITLE
> Actually, you can directly pass in a URL to `avatar`

### ISSUE THREAD

**Issue by calalloo** [nanxiaobei/hugo-paper#198]
> Actually, you can directly pass in a URL to `avatar`

How? I added `avatar = "images/avatar.webp"` under `params and still the gravatar URL shows up.

_Originally posted by @calalloo in https://github.com/nanxiaobei/hugo-paper/issues/181#issuecomment-1732671164_

**Comment by nanxiaobei** [comment]
Should be an absolute url, it depends on your folder structure.
