### ISSUE TITLE
当代码块内容宽度过宽的时候，代码块不会缩放展示

### ISSUE THREAD

**Issue by naodeng** [nanxiaobei/hugo-paper#203]
![d3WvMs](https://cdn.jsdelivr.net/gh/naodeng/blogimg@master/uPic/d3WvMs.png)

问题 url：[https://naodeng.tech/post/supertest-tutorial-building-your-own-project-from-0-to-1/](https://naodeng.tech/post/supertest-tutorial-building-your-own-project-from-0-to-1/)

大佬有调整的思路吗

**Comment by nanxiaobei** [comment]
升级到 `6.24`，看是否已修复。
未修复的话请留言。

**Comment by naodeng** [comment]
![943fs3](https://cdn.jsdelivr.net/gh/naodeng/blogimg@master/uPic/943fs3.png)
代码块样式变得好奇怪

**Comment by nanxiaobei** [comment]
再更新一下，这次没升版本号，直接拉取更新即可。

**Comment by naodeng** [comment]
正常显示了，感谢大佬
