### ISSUE TITLE
facing problem in setting up homepage

### ISSUE THREAD

**Issue by kohinoor23** [nanxiaobei/hugo-paper#204]
<img width="136" alt="image" src="https://github.com/nanxiaobei/hugo-paper/assets/61497490/4bee7e40-cb39-4534-9bf5-f38463ac486c">
This is my directory structure. When I delete the bookLog folder, I get the usual homepage with the avatar, and the posts list. 
But in the current structure, the homepage shows to be blank. I want the posts to shown up as list on homepage, with the gravatar avatar. How to accomplish this without the blank page showing?

layouts is empty for now.

**Comment by nanxiaobei** [comment]
You can refer to this structure https://github.com/nanxiaobei/hugo-paper/tree/main/exampleSite/content
