### ISSUE TITLE
how to add text on list page?

### ISSUE THREAD

**Issue by kohinoor23** [nanxiaobei/hugo-paper#205]
<img width="554" alt="image" src="https://github.com/nanxiaobei/hugo-paper/assets/61497490/08bb03f4-8e9d-4ea0-b794-3c713e821028">

How to add some text in the desired location? 

(also is there any better ways to resolve these doubts? Feels like wasting issues here and disturbing the admin)

**Comment by nanxiaobei** [comment]
maybe you can edit in here:
https://github.com/nanxiaobei/hugo-paper/blob/main/layouts/_default/list.html#L4

by naturally this theme only support page title on "tags" page.
