### ISSUE TITLE
how to add images in post using html?

### ISSUE THREAD

**Issue by kohinoor23** [nanxiaobei/hugo-paper#206]
I tried adding images using ```![name](path)``` syntax and it works. The images are too big, so I replaced with this:   

```html  
<figure>
  <img src="same path as above" alt="altt" width = "500px">
  <figcaption>caption</figcaption>
</figure>  
```

Now no images display. Any suggestions to correct/execute this?

**Comment by nanxiaobei** [comment]
This is a question related to Hugo, and `hugo-paper` is just a Hugo theme.
