### ISSUE TITLE
Long links are not wrapped 

### ISSUE THREAD

**Issue by aecra** [nanxiaobei/hugo-paper#207]
Like this.

![Screenshot_2023-12-14-09-07-41-433_com.android.chrome-edit.jpg](https://github.com/nanxiaobei/hugo-paper/assets/34883050/701765ae-c9bc-420a-adc8-a64fb103647d)

**Comment by nanxiaobei** [comment]
Can you please provide the url of this page?

**Comment by aecra** [comment]
The url is https://aecra.github.io/article/network-encoding-and-decoding-algorithm-in-p2p-file-sharing-system/ .

I found that this problem occurs in chrome and edge, but Firefox does not have this problem.

**Comment by nanxiaobei** [comment]
Please upgrade to `6.25.0` to try.
