### ISSUE TITLE
Setting dark, light, or auto default mode 

### ISSUE THREAD

**Issue by gaveen** [nanxiaobei/hugo-paper#210]
Is it possible to use a configurations to specify the the preferred mode between light, dark, and auto?

I couldn't find anything documented and I'm curious how it'll affect Giscus themes, if at all.

**Comment by nanxiaobei** [comment]
1. default is `light`, you can add `dark` to html class to set the default to dark: https://github.com/nanxiaobei/hugo-paper/blob/main/layouts/_default/baseof.html#L37 `class="not-ready lg:text-base dark"`
2. not have affect to Giscus themes
