### ISSUE TITLE
Disabling gravatar animation

### ISSUE THREAD

**Issue by gaveen** [nanxiaobei/hugo-paper#211]
Is currently possible to rotating animation used with the gravatar image?

**Comment by nanxiaobei** [comment]
you can remove `hover:animate-spin` class here: https://github.com/nanxiaobei/hugo-paper/blob/main/layouts/_default/list.html#L29

from 
`"my-0 aspect-square w-16 rounded-full !bg-black/5 hover:animate-spin dark:!bg-black/80"`
to
`"my-0 aspect-square w-16 rounded-full !bg-black/5 dark:!bg-black/80"`
