### ISSUE TITLE
giscus 不随主题自动切换 light/dark 模式

### ISSUE THREAD

**Issue by hxglife** [nanxiaobei/hugo-paper#220]
小北你好，我在使用 paper 的 giscus 评论时遇到一个问题，giscus 无法跟随主题的 light/dark 模式进行切换。我搜索了相关的信息，部分主题是可以支持的。请问在 paper 里如何修改代码能够实现，是否可以更新这个功能？感谢。
---
ref:
- https://github.com/giscus/giscus/issues/336
- https://github.com/giscus/giscus/issues/1200
- https://12x.me/posts/2023-04-18-hugo-giscus
- https://hugomods.com/docs/comment-engines/giscus/
- https://zhang-weiming.github.io/post/tutorial/hugo_giscus/
- https://www.lixueduan.com/posts/blog/02-add-giscus-comment/

**Comment by nanxiaobei** [comment]
giscus 为 PR 引入 https://github.com/nanxiaobei/hugo-paper/pull/195，非核心功能，
欢迎 PR 或联系原 PR 开发者增加新功能。
