### ISSUE TITLE
 html 渲染方式和 giscus 存在冲突

### ISSUE THREAD

**Issue by hxglife** [nanxiaobei/hugo-paper#221]
小北你好，paper 主题启用 giscus 评论时，在正文CJK字符很多的时候，会导致 giscus 报错 URI TOO LONG。

我看了代码，layouts/partials/head.html 的第 22 行：`<meta name="description" content="{{ .Summary }}" />`

默认的主题配置下，在渲染 html 时会把文章正文全部输出在 description 里（如果文章比较长，会有几万个字符），而 giscus 的 js 在加载时会调用到这里作为 URI 的一部分，造成 URI 太长报错。

目前我在 config 里加了 `hasCJKLanguage = 'true'` 之后，description 的长度正常了。giscus 也不再报错。麻烦定位一下问题的确切原因并修复，感谢。

ref
- https://hugo-docs.netlify.app/getting-started/configuration/

**Comment by nanxiaobei** [comment]
giscus 为 PR 引入 https://github.com/nanxiaobei/hugo-paper/pull/195，非核心功能，
欢迎 PR 或联系原 PR 开发者增加新功能。
