### ISSUE TITLE
Option to remove the dark mode icon entirely

### ISSUE THREAD

**Issue by Kernald** [nanxiaobei/hugo-paper#232]
`monoDarkIcon` allows for replacing the icon, but I'd love an option to remove it entirely. With more and more browsers behaving properly with `prefers-color-scheme`, I don't personally value having an option at all and would prefer seeing it gone.

**Comment by nanxiaobei** [comment]
no plan to add an option now. you can just remove these lines:
https://github.com/nanxiaobei/hugo-paper/blob/main/layouts/partials/header.html#L8-L12
