### ISSUE TITLE
It is not possible to make Gravatar stop working to put a profile image in the circle on the Home page

### ISSUE THREAD

**Issue by dudsdev96** [nanxiaobei/hugo-paper#234]
I'm trying to place a JPG image in the avatar circle on the Home page (where figures are being pulled from Gravatar automatically) through the params in hugo.toml configuration archive (like the hugo documentation) and it's not possible to stop this without touching it manually and breaking the theme (application)

**Comment by nanxiaobei** [comment]
if you do not want to use gravatar, you can pass an image url to `avatar`
