### ISSUE TITLE
Avatar image How to put with the URL

### ISSUE THREAD

**Issue by dudsdev96** [nanxiaobei/hugo-paper#235]
Sorry for the inconvenience, could you please show me how to put the image on the avatar using the URL? I tried different ways and I didn't succeed, here are the prints.
![1](https://github.com/nanxiaobei/hugo-paper/assets/169103163/107c6003-3549-409a-9f18-b03ab6244669)
![2](https://github.com/nanxiaobei/hugo-paper/assets/169103163/39d25cf5-d900-411b-bbfd-3d8d346cfd46)
![3](https://github.com/nanxiaobei/hugo-paper/assets/169103163/61abb4d1-0da2-4df7-8023-80178f8aaed8)
![4](https://github.com/nanxiaobei/hugo-paper/assets/169103163/b2f9d971-9491-4760-9197-0428d86fbe0b)

**Comment by nanxiaobei** [comment]
you need to upload the image to a server, and then pass the uploaded image url to `avartar`
