### ISSUE TITLE
Make rss-button link to specific feed on the page

### ISSUE THREAD

**Issue by neshtea** [nanxiaobei/hugo-paper#238]
If you configure the site to show the rss-button via

```yaml
params:
  rss: true
```

the button seems to always refer to `/index.xml`. Is it possible to configure where the url points, say for example `/posts/index.xml`?

**Comment by nanxiaobei** [comment]
It'll need to customize rss templates(https://gohugo.io/templates/rss/), currently no plan to add them, thanks.
