### ISSUE TITLE
Function "endif" not defined

### ISSUE THREAD

**Issue by hongster** [nanxiaobei/hugo-paper#241]
https://github.com/nanxiaobei/hugo-paper/blob/26a1c4cd16409aedc54ba5521d0b67e1d7ffa7c7/layouts/partials/footer.html#L10C5-L10C10

`parse failed: template: partials/footer.html:10: function "endif" not defined`

It should be "end" instead of "endif".

**Comment by nanxiaobei** [comment]
https://github.com/nanxiaobei/hugo-paper/pull/240
