### ISSUE TITLE
`.Site.DisqusShortname` was deprecated in Hugo v0.120.0

### ISSUE THREAD

**Issue by hongster** [nanxiaobei/hugo-paper#243]
**Issue**

* Unable to build due to usage of deprecated site method, `DisqusShortname`

E**rror message when building**

> ERROR deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.134.0. Use .Site.Config.Services.Disqus.Shortname instead.

**Affected file**

* /layouts/_default/single.html

**Comment by nanxiaobei** [comment]
please update the theme
