### ISSUE TITLE
Bluesky icon and support

### ISSUE THREAD

**Issue by bdon** [nanxiaobei/hugo-paper#249]
Hi, thanks for this nice looking and simple theme. Bluesky has been getting popular, would you be open to adding support for that similar to Mastodon in https://github.com/nanxiaobei/hugo-paper/issues/132 ?

Thanks!

**Comment by eduardomps** [comment]
seconded, the network already reached 24 M users, and has reached the headlines in mainstream media

**Comment by nanxiaobei** [comment]
added bluesky on version `6.28`

**Comment by bdon** [comment]
Works great, thank you!

**Comment by SebastianCallh** [comment]
Hello, and thanks for this theme!
I tried using the bluesky integration and set the params.bluesky to my ID, and sure enough the link appears next to the other SoMe icons. However, it points to `https://bluesky.com/ID` and not `https://bsky.app/profile/ID`. I cannot figure out why this is, do you have any advice? My theme submodule is `8eeb1e8a513d3a0e32e0b305d445c3f6d545eeb3`, which should correspond to the `6.28` release.

**Comment by SebastianCallh** [comment]
I figured it out. I had a custom header.html which was the cause. It looks like the code defaults to creating a .com link if it could not find the name in the if-else clause, which was what confused me.
