### ISSUE TITLE
How to edit 'about' and add 'posts' links on the upper right menu?

### ISSUE THREAD

**Issue by hughshuwang** [nanxiaobei/hugo-paper#25]
In the default setting of the template, we don't have anything in the hidden list by clicking the upper right button, but in the demo site, there's an 'about' page. How to add that?

Thanks!

**Comment by morristai** [comment]
@hughshuwang  Hi, could I kindly ask you how you solved this problem? Thanks

**Comment by nanxiaobei** [comment]
@morristai https://gohugo.io/content-management/menus/

**Comment by morristai** [comment]
@nanxiaobei  Thanks :)
