### ISSUE TITLE
Generate URLs using absURL and friends

### ISSUE THREAD

**Issue by flexchar** [nanxiaobei/hugo-paper#32]
Nice theme but has large flaw by using manual link concatenation. 

[Real example:](https://github.com/nanxiaobei/hugo-paper/blob/master/layouts/partials/footer.html#L9)
```html
<script src="{{.Site.BaseURL}}js/instantclick.min.js" data-no-instant></script>
```
would be much better off using `absURL`
```html
<script src="{{ "js/instantclick.min.js" | absURL }}" data-no-instant></script>
```

Very good explanation here: https://discourse.gohugo.io/t/how-not-to-specify-url-site/5691/5
Another recommendation by @bep: https://github.com/gohugoio/hugo/issues/3262#issuecomment-290991303
Cheers!

**Comment by nanxiaobei** [comment]
Hi, thanks for your suggestion, now `4.0` has released, with new look and absURL inside, you can try it.

**Comment by flexchar** [comment]
Well done @nanxiaobei!
