### ISSUE TITLE
Example page/config would make it easier to get started

### ISSUE THREAD

**Issue by jpolack** [nanxiaobei/hugo-paper#35]
I have some troubble to get started, because I don't know which params should be set. An example config or documentation would make it easier to get started.

Greets

**Comment by nanxiaobei** [comment]
`[[menu.main]]` for [Menus](https://gohugo.io/content-management/menus/) and `type = "page"` [Front Matter](https://gohugo.io/content-management/front-matter/) for "page"(can appear in menu but not in post list). For other config, just read [Hugo docs](https://gohugo.io/getting-started/configuration/), it's not the theme's feature, thanks.
