### ISSUE TITLE
add an exampleSite 

### ISSUE THREAD

**Issue by itsjzt** [nanxiaobei/hugo-paper#36]
exampleSite are very good reference of all the features and things possible with theme.

It will document the theme in very good way. so please add it.

**Comment by nanxiaobei** [comment]
From Hugo docs: https://gohugo.io/contribute/themes/#adding-a-theme-to-the-list

> * If your theme doesn’t fit into the Hugo Basic Example site, we encourage theme authors to supply a self-contained Hugo site in /exampleSite/.

`hugo-paper` is very simple and fits in the Hugo Basic Example site, so no need to add an `exampleSite`, just see the theme's demo here: https://nanxiaobei.github.io/hugo-paper/

Thanks.

**Comment by itsjzt** [comment]
OK, btw thanks for this nice theme.
