### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by zhixiangyuan** [nanxiaobei/hugo-paper#37]
您好，我在使用中发现了几个问题

1. 文章没有目录
2. 封面展示的时候，如果里面的内容是代码块，整个就乱掉了。![image](https://user-images.githubusercontent.com/25138766/60749873-276ecf00-9fd3-11e9-9195-cd0c49087f75.png)
3. 表格样式太丑了
![image](https://user-images.githubusercontent.com/25138766/60749861-f2627c80-9fd2-11e9-938a-765cf2ec4f62.png)
下面的好看很多
![image](https://user-images.githubusercontent.com/25138766/60763190-a3cfe380-a0a1-11e9-82ab-5ce388945cb6.png)
4. 目录需要点击两个小横杠才能打开，但是打开之后字体很大，有一种老年人的感觉。
![image](https://user-images.githubusercontent.com/25138766/60749892-5edd7b80-9fd3-11e9-8116-8bd112b41988.png)
能够支持将目录添加在第一行等的方式，毕竟第一行占用的空间也不大，而且除了这些一般也不放别的东西。
![image](https://user-images.githubusercontent.com/25138766/60749989-b5978500-9fd4-11e9-9b08-05786ca32275.png)
![image](https://user-images.githubusercontent.com/25138766/60749905-98ae8200-9fd3-11e9-8371-ff2fb8aeea90.png)
5. 首页是有颜色的，点击文章进去之后一片纯白，有一种走到了别的网站的感觉。希望能够将首页的颜色顺带到文章的页面，保持网站的一体感。
6. 归档的页面和分类的页面个人觉得没有必要和主页一样显示文章的内容。归档的页面完全可以按照时间分类，只显示标题。分类的页面也是如此，没有必要显示内容，可以节省出很多空间，显示出更多的文章。
![image](https://user-images.githubusercontent.com/25138766/60749971-6cdfcc00-9fd4-11e9-96e7-8e4c8683b138.png)

**Comment by nanxiaobei** [comment]
你好，感谢反馈~

Paper 主题的本义是想提供一个最小可用的专注于文字的主题，并不会去添加过多的功能。
如有其它需要，建议自行 fork 主题在其基础上修改。

1. 文章没有目录


不考虑添加此功能，可自行实现。

2. 封面展示的时候，如果里面的内容是代码块，整个就乱掉了


这个暂时没有好的解决办法，会在 4.1 版本中考虑 CSS 控制板块的高度，优化 UI。

3. 表格样式太丑了


表格是 html 默认表现中比较难控制的一个东西，如果有个别栏文字过长（如「描述」），就会积压其他栏，这是浏览器的默认实现。
会在 4.1 中试图加入少量 CSS 控制。

4. 目录需要点击两个小横杠才能打开，但是打开之后字体很大，有一种老年人的感觉。


设计如此，会考虑优化菜单项间距优化。暂不考虑实现为顶部展示菜单。

5. 首页是有颜色的，点击文章进去之后一片纯白，有一种走到了别的网站的感觉。能够将首页的颜色顺带到文章的页面，保持网站的一体感。
> 6.
> 归档的页面和分类的页面个人觉得没有必要和主页一样显示文章的内容。归档的页面完全可以按照时间分类，只显示标题。分类的页面也是如此，没有必要显示内容，可以节省出很多空间，显示出更多的文章。


设计如此，后续可能会变，但暂时不会有变化，可考虑自行修改。

zhixiangyuan <notifications@github.com> 于2019年7月6日周六 上午10:00写道：

**Comment by arcfree** [comment]
你好,我有个问题想请教,假如文章多了,没有目录索引,只靠翻页来定位很麻烦,,可以给个自动生成目录索引的功能不...

**Comment by nanxiaobei** [comment]
你好，目前暂无添加分页功能的计划
