### ISSUE TITLE
Image not loaded cause of instantClick

### ISSUE THREAD

**Issue by doliG** [nanxiaobei/hugo-paper#38]
Hello,

I discovered you're theme on the Hugo store and just fall in love with it. It's so clean and simple, just wow 👏 

However, I experiment curious behavior with the instantSearch feature.

Scenario to reproduce:
- Given that I'm on the home page
- And I click on a post
- Then the post images aren't displayed (see screenshot below)

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/24778042/61558178-9b46b800-aa66-11e9-8e8a-767cedcdacb2.png">

However, when I disable JS (or I reload the post page), everything works fine.

Let me add that I use the `$ hugo serve -D` for development purpose :)

Thanks.

**Comment by nanxiaobei** [comment]
Thanks for your response.
After test, I found that the markdown image loaded correctly, so I don't really know how to reproduce it. 
But `InstantClick` is weird in some case, and you can just remove `InstantClick`(js file and `InstantClick.on('change', ...)`) inside `layouts/partials/footer.html` to make things right.
