### ISSUE TITLE
List Layout For Single Post Too

### ISSUE THREAD

**Issue by BayuAngora** [nanxiaobei/hugo-paper#40]
Dear All 

I like the list layout that framed on white background like this -> 
https://i.postimg.cc/h4X7JTkv/IMG-20190820-113258.jpg

I want to use that layout for single page and single post too ->
https://i.postimg.cc/XYbZDhpB/IMG-20190820-113422.jpg

I changed the article class to "post-entry" but the layout can't be same as list layout? 
https://github.com/BayuAngora/paper/blob/master/layouts/_default/single.html

Regards

**Comment by nanxiaobei** [comment]
You need to move css `background: ...` in class `.list` to `body`.

**Comment by BayuAngora** [comment]
> You need to move css `background: ...` in class `.list` to `body`.

It works. Thanks.
