### ISSUE TITLE
想问下是否是缺了什么配置

### ISSUE THREAD

**Issue by xiaoheiAh** [nanxiaobei/hugo-paper#41]
我看了下 config.toml 里没有 `RegularPages` 我加上了.但是还是报错

`Building sites … ERROR 2019/08/22 13:09:38 render of "taxonomyTerm" failed: "/Users/otis.z/xiaoheiah/blog/themes/paper/layouts/_default/list.html:13:39": execute of template failed: template: _default/list.html:13:39: executing "_default/list.html" at <$pctx.RegularPages>: can't evaluate field RegularPages in type *hugolib.pageState
ERROR 2019/08/22 13:09:38 render of "taxonomy" failed: "/Users/otis.z/xiaoheiah/blog/themes/paper/layouts/_default/list.html:13:39": execute of template failed: template: _default/list.html:13:39: executing "_default/list.html" at <$pctx.RegularPages>: can't evaluate field RegularPages in type *hugolib.pageState
ERROR 2019/08/22 13:09:38 render of "taxonomy" failed: "/Users/otis.z/xiaoheiah/blog/themes/paper/layouts/_default/list.html:13:39": execute of template failed: template: _default/list.html:13:39: executing "_default/list.html" at <$pctx.RegularPages>: can't evaluate field RegularPages in type *hugolib.pageState
ERROR 2019/08/22 13:09:38 render of "taxonomy" failed: "/Users/otis.z/xiaoheiah/blog/themes/paper/layouts/_default/list.html:13:39": execute of template failed: template: _default/list.html:13:39: executing "_default/list.html" at <$pctx.RegularPages>: can't evaluate field RegularPages in type *hugolib.pageState
Total in 22 ms
Error: Error building site: failed to render pages: render of "taxonomy" failed: "/Users/otis.z/xiaoheiah/blog/themes/paper/layouts/_default/list.html:13:39": execute of template failed: template: _default/list.html:13:39: executing "_default/list.html" at <$pctx.RegularPages>: can't evaluate field RegularPages in type *hugolib.pageState`

**Comment by nanxiaobei** [comment]
升级一下 Hugo 试试，这个 `RegularPages` 是配合 Hugo v.0.57.0 升级改的

**Comment by xiaoheiAh** [comment]
升级可以了~感谢. 但是代码高亮有问题
![image](https://user-images.githubusercontent.com/27981726/63492647-69ed5c00-c4ec-11e9-92b7-124648c3c422.png)

**Comment by xiaoheiAh** [comment]
不支持 rust

**Comment by nanxiaobei** [comment]
看了一下，应该是默认引入的 highlight.js 中没有支持 rust，你可以自行修改一下：

https://highlightjs.org/download/

在这里把 rust 勾上，然后下载文件替换主题中的 `/static/highlight.min.js`。

或者使用这种语法：

```
{{< highlight rust >}}
println!("{:?}", foo);
{{< / highlight >}}
```
