### ISSUE TITLE
min_version in theme.toml is invalid

### ISSUE THREAD

**Issue by onedrawingperday** [nanxiaobei/hugo-paper#43]
Hello @nanxiaobei 

Please change [this line](https://github.com/nanxiaobei/hugo-paper/blob/master/theme.toml#L11) to `min_version = "0.57.1"` because `0.57.1` is the minimum Hugo version that your theme can work with since https://github.com/gohugoio/hugoThemes/issues/682 was fixed.

**Comment by nanxiaobei** [comment]
Ok, Thanks for reminding me.
