### ISSUE TITLE
"Next" appears in Chinese

### ISSUE THREAD

**Issue by felipe1982** [nanxiaobei/hugo-paper#5]
If you take a look at http://static.felipe1982.com you can see that the "next" link at the bottom appears in Chinese. How can I modify this?

![image](https://user-images.githubusercontent.com/275621/39436675-455bd0e0-4cd1-11e8-9c28-38a0ec674467.png)

**Comment by nanxiaobei** [comment]
hi, you can change it in "/layouts/_default/list.html".
