### ISSUE TITLE
First content title overlaps site title on mobile

### ISSUE THREAD

**Issue by camhashemi** [nanxiaobei/hugo-paper#50]
<img width="386" alt="Screen Shot 2019-11-16 at 5 23 27 PM" src="https://user-images.githubusercontent.com/8929238/68996110-f0200100-0895-11ea-8c03-164563f950e8.png">

**Comment by camhashemi** [comment]
I don't have any custom styling, and my `content` directory is flat. Please let me know if you need any more info.

**Comment by nanxiaobei** [comment]
Hi, You can just update the theme to v4.4~
