### ISSUE TITLE
Hugo Site does not properly display when using Hugo Paper

### ISSUE THREAD

**Issue by felipe1982** [nanxiaobei/hugo-paper#51]
Checkout my branch https://github.com/felipe1982/hugo-blog/tree/broken-hugo-paper and run "hugo server" and see that the site does not properly load.

![image](https://user-images.githubusercontent.com/275621/72235956-aa2ab380-3620-11ea-8b99-7d44e861e62f.png)

**Comment by nanxiaobei** [comment]
Try upgrade Hugo to the latest version.

**Comment by felipe1982** [comment]
Yes sir. I have.

**Comment by felipe1982** [comment]
We're you able to reproduce the issue? Have you released a fix? Why was this issue closed with comment?

**Comment by nanxiaobei** [comment]
Thanks for your feedback.
Now the theme has upgraded, please upgrade to `4.5` to fix this.
