### ISSUE TITLE
taxonomy is not working

### ISSUE THREAD

**Issue by huijunchen9260** [nanxiaobei/hugo-paper#52]
Today I just applied this theme to my personal website. It works well, and I love it!

I wonder whether it is possible to add taxonomy support to this theme.

Like the following screenshot, if I click on a taxonomy, say "Hugo", I cannot really screen out only the posts with "Hugo" taxonomy. Does it possible to have such function?

Thank you!

![image](https://user-images.githubusercontent.com/54217138/76165921-3513c000-6131-11ea-97fd-27e4ef255f8f.png)

**Comment by nanxiaobei** [comment]
Sorry this theme only supports tags, not support taxonomy.
You can add it yourselft~

**Comment by huijunchen9260** [comment]
So even if I click on the tags and it does not really group the together, it is still normal?

Thank you!

**Comment by nanxiaobei** [comment]
Tags should work, 
like `markdown` tag: https://nanxiaobei.github.io/hugo-paper/tags/markdown/
And it's just the Hugo's tags feature, nothing to do with this theme~

**Comment by huijunchen9260** [comment]
But somehow my tags doesn't work, like this:

https://huijunchen9260.github.io/tags/shell-scripting/

Every blog posts show in the tag "shell-scripting", even though only one post has such tag.

The following is my preamble:

```
---
title: "Shell Scripting Tips"
date: 2019-11-09T18:46:16-05:00
draft: false
tags:
- Shell Scripting
---
```

Hope that you can help me with this!

**Comment by nanxiaobei** [comment]
Thanks for your feedback, no the taxonomy problem has been fixed.
You can upgrade to `v4.6` to have a try.

**Comment by huijunchen9260** [comment]
Thank you! It works like a charm!

Just one point right now, like the following picture:

![image](https://user-images.githubusercontent.com/54217138/76234399-10d2e480-6200-11ea-92b5-d7f9fd208568.png)

When I click blog, the title is not blog but tags. 

https://huijunchen9260.github.io/blog/

May I ask how should I adjust it?

(I also what to ask how to activate dark mode =w=)

**Comment by nanxiaobei** [comment]
What's the type of the "Blog" page?
The dark mode will active automatically, based on the time of a day.

**Comment by huijunchen9260** [comment]
content
├── about.md
├── blog
│   ├── ArchTips.md
│   ├── Dmenufm_Bugs.md
│   ├── hugonote
│   │   ├── HugoNote1.png
│   │   ├── HugoNote.md
│   │   └── HugoNote.pdf
│   ├── _index.md
│   └── ShellTips.md
└── research.md

2 directories, 9 files

This is the tree for content folder.

The "Blog" page is the in the blog directory

The content of the `_index.md` is:

```
---
title: "Blog"
date: 2019-11-10T00:13:58-05:00
menu: "main"
showDate: true
---
```

**Comment by nanxiaobei** [comment]
Try the new code again.
If title "Blog" become "Blogs", try this: https://discourse.gohugo.io/t/how-can-i-stop-section-title-from-showing-up-as-plural/994

**Comment by huijunchen9260** [comment]
Thank you! It works like a charm and also that possible plural issue doesn't appear!
Thank you very much!
