### ISSUE TITLE
How does dark mode work

### ISSUE THREAD

**Issue by donnydark0** [nanxiaobei/hugo-paper#53]
Hi,

how exactly does dark mode work? I am wondering, because switching appearance on a mac does not seem to have an effect on the website (on other sites I can switch betweeen dark/light and the site changes accordingly immediately). Is it triggered by something else? Best

**Comment by nanxiaobei** [comment]
It automatically switches according to the time of a day. It turns dark at night and bright during the day, just like the auto switch in iOS.

**Comment by donnydark0** [comment]
I see, so it uses its own timer instead of following the preferred color scheme of the OS.

**Comment by nanxiaobei** [comment]
yeah that's right
