### ISSUE TITLE
how to set pre code white-space:pre at ios safari

### ISSUE THREAD

**Issue by Charles-one** [nanxiaobei/hugo-paper#54]
1. how to set pre code white-space:pre at ios safari, 如何设置在ios移动端代码块不换行, 空格和换行符仍然保存.
2. 对比图片, pc和ios
![img345](https://user-images.githubusercontent.com/48158066/79408303-9a2ec100-7fcd-11ea-853a-12b71bbd8258.png)
<img width="373" alt="365" src="https://user-images.githubusercontent.com/48158066/79408385-c5b1ab80-7fcd-11ea-80ca-806d40f2bf10.png">
3. 

> .post-content code {
  margin-left: 4px;
  margin-right: 4px;
  padding: 4px 6px;
  font-family: Menlo, Monaco, 'Courier New', Courier, monospace;
  font-size: 0.95em;
  line-height: 1.5;
  background: var(--code-bg);
  border-radius: 2px;
  white-space: pre;
}
.post-content pre code {
  display: block;
  margin-left: 0;
  margin-right: 0;
  padding: var(--gap);
  color: rgba(255, 255, 255, 0.8);
  /*background: transparent;*/
  background: rgba(40, 44, 52, 1);
  border-radius: 0;
  white-space: pre;
}

**Comment by nanxiaobei** [comment]
目前未对 iOS 做特殊处理，请自行使用 CSS 实现
