### ISSUE TITLE
新建的文章在首页无法显示，但是在 http://localhost:1313/posts 下可以显示

### ISSUE THREAD

**Issue by slarkcoder** [nanxiaobei/hugo-paper#57]
<img width="1657" alt="CleanShot 2020-06-19 at 09 08 00@2x" src="https://user-images.githubusercontent.com/8657857/85086214-82adc780-b20c-11ea-8034-9d5e85756969.png">

请问可能是我哪里出错了吗，thx！

**Comment by nanxiaobei** [comment]
可尝试放到 `post` 目录下。

**Comment by h0wardch3ng** [comment]
@nanxiaobei 
https://github.com/gohugoio/hugoBasicExample/tree/master/content 
Please use standard directory structure path.

**Comment by junjieyuan** [comment]
可能是本主题没有```layouts/index.html```导致的？
可以看一下 [ananke](https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/index.html)。
