### ISSUE TITLE
不显示文章

### ISSUE THREAD

**Issue by zsq2010** [nanxiaobei/hugo-paper#58]
只能提交hugo new xxx.md第一级别的文章

但是,不能 new post/xxx

而且,界面也不对

![图片](https://user-images.githubusercontent.com/4374659/88400865-84fed500-cdfb-11ea-8e68-213a0c08baa1.png)

**Comment by nanxiaobei** [comment]
请参考 Hugo 官方示例 https://github.com/gohugoio/hugoBasicExample 下目录结构，
`hugo-paper` 以此为模版开发，或可升级 hugo 版本再次尝试。
