### ISSUE TITLE
Is it possible to pin post to the top of the webpage

### ISSUE THREAD

**Issue by piojanu** [nanxiaobei/hugo-paper#6]
Hi!

First of all thanks for this theme! It's really straightforward and good looking 👍 

I have a question though, is it possible (or how to make it possible) to pin some post to the top of the site? So I can e.g. write my biography and pin it, so it is at the top of the page (like "Create a New Theme" in your demo).

Thanks for help!

**Comment by nanxiaobei** [comment]
Hi, it's actually depends on Hugo, and as far as I know, Hugo doesn't seem to have a feature for that, there might be a hack way to implement it, but likely to pay a disproportionate price, so sorry for that.

**Comment by piojanu** [comment]
Ok, I thought about better way. I’ll just edit layout of posts list and add my image and short bio at the top :)
But still, this theme is really helpful as a base for further customisation. It’s really straightforward and clean! I’m using Hugo for the first time and I was able to understand what is going on in your theme to adjust it for my needs (I’m not a web developer too!).

Thanks for your time!

Pozdrawiam,
Piotr Januszewski
