### ISSUE TITLE
Homepage: index page.

### ISSUE THREAD

**Issue by jtagcat** [nanxiaobei/hugo-paper#60]
Provide the ability to change the first post (Markdown Syntax Guide)'s spot to static text.

![image](../raw/master/images/screenshot.png)

**Comment by nanxiaobei** [comment]
Sorry, no plan to add this feature now, you can fork and customize it for yourself.

**Comment by jtagcat** [comment]
I think having it as an optional opt-in feature. I thought it would be better to not fork, as having more features than upstream might pull users to my fork, thus moving upstream to the fork.

**Comment by jtagcat** [comment]
This feature is available at a fork: https://gitlab.com/hugo-plains/hugo-plains
