### ISSUE TITLE
Blank page after running 'hugo server'

### ISSUE THREAD

**Issue by justirma** [nanxiaobei/hugo-paper#7]
Showing a blank page on my local after running `hugo server`. No errors appear in my console nor in the command line. 

Screenshot of my directory: 
<img width="1016" alt="hugopaper" src="https://user-images.githubusercontent.com/12990243/40252132-60683d5c-5aa9-11e8-8a65-0c81739c5745.png">

Added a `config.toml` with this inside
-----
baseURL = "/"
languageCode = "en-us"
title = "ProdShip"
author = "" 
theme= "hugo-paper"
-----

**Comment by nanxiaobei** [comment]
Maybe no drafts
