### ISSUE TITLE
Can you share example site in the code it will be great if you do so, because I am new to hugo.

### ISSUE THREAD

**Issue by KetanIP** [nanxiaobei/hugo-paper#76]

**Comment by kdkasad** [comment]
I believe this is the exampleSite in use: https://github.com/gohugoio/HugoBasicExample

It would also be great if you could shorten the title to 1 sentence and put the rest of the informtion in the description.

**Comment by nanxiaobei** [comment]
Yes, it's the Hugo official example https://github.com/gohugoio/HugoBasicExample
