### ISSUE TITLE
Menu dropdown not working

### ISSUE THREAD

**Issue by mr-islam** [nanxiaobei/hugo-paper#8]
Hi, I really love this theme, awesome work :+1: 

I've found one issue: one mobile and tablet devices, the tapping the menu dropdown (two horizontal lines) doesn't do anything, so the menu cannot be accessed.

I tried this on the demo website, and by using the theme on my own site. Even on desktop when the browser is resized, clicking the `=` on the top-right does not show the menu. Like in this screenshot:

[!image](https://i.imgur.com/KjUgrTY.png)

**Comment by nanxiaobei** [comment]
Actually, you must refresh page after resize, to let this button work, it's "designed" in this way.

**Comment by mr-islam** [comment]
Thank you for your reply! The theme is fine I did something wrong :smile: 

Refreshing the page is working on the [demo site](https://themes.gohugo.io/theme/hugo-paper/), but not for me on [my site](https://navedislam.com/)… if you don't mind can you please help me find my problem?

I am using a slightly modified Hugo-Paper theme, and my [repository is here](https://github.com/mr-islam/navedislam.com-v3) — but I didn't touch the menu parts so I'm confused why it isn't working.

Any help would be appreciated

**Comment by nanxiaobei** [comment]
Hi, because you've removed "highlight.min.js" file, but inside <scripts> if called "hljs.initHighlightingOnLoad(); ...", no "hljs" here, so throw an error. 
you can change js code to this
`
<script data-no-instant>
menuToggle();
InstantClick.on('change', function() {
  menuToggle();
});
function menuToggle() {
  var $toggle = document.querySelector('.menu-toggle');
  if (!$toggle.offsetParent) {
    return;
  }
  var $body = document.querySelector('body');
  $toggle.addEventListener('click', function() {
    $body.classList.toggle('noscroll');
  }, false);
}
</script>
`
to fix the error.

**Comment by nanxiaobei** [comment]
Hi, because you've removed "highlight.min.js" file, but inside if called "hljs.initHighlightingOnLoad(); ...", no "hljs" here, so throw an error.
you can change js code to this
```js
menuToggle();
InstantClick.on('change', function() {
  menuToggle();
});
function menuToggle() {
  var $toggle = document.querySelector('.menu-toggle');
  if (!$toggle.offsetParent) {
    return;
  }
  var $body = document.querySelector('body');
  $toggle.addEventListener('click', function() {
    $body.classList.toggle('noscroll');
  }, false);
}
```
to fix the error.

**Comment by nanxiaobei** [comment]
Hi, because you've removed "highlight.min.js" file, but inside <script> if called "hljs.initHighlightingOnLoad(); ...", no "hljs" here, so throw an error.
you can change js code to this

```js
menuToggle();
InstantClick.on('change', function() {
  menuToggle();
});
function menuToggle() {
  var $toggle = document.querySelector('.menu-toggle');
  if (!$toggle.offsetParent) {
    return;
  }
  var $body = document.querySelector('body');
  $toggle.addEventListener('click', function() {
    $body.classList.toggle('noscroll');
  }, false);
}
```

to fix the error.

**Comment by mr-islam** [comment]
THANK YOU SO MUCH!!

I was looking in the `header.html` file so much, and I forgot to check `footer.html`! It is working perfect now

Thank you again for your kind help @nanxiaobei :heart: !
