### ISSUE TITLE
Github Dependabot alerts

### ISSUE THREAD

**Issue by Charles-one** [nanxiaobei/hugo-paper#81]
Dependabot couldn't find a package.json
Dependabot couldn't find a package.json.

Dependabot requires a package.json to evaluate your JavaScript dependencies. It had expected to find one at the path: /package.json.

Learn more about troubleshooting Dependabot errors.

2 highlight.js vulnerabilities found in highlight.min.js on Nov 25, 2020
Remediation
Upgrade highlight.js to version 10.4.1 or later.

Always verify the validity and compatibility of suggestions with your codebase.

**Comment by nanxiaobei** [comment]
It‘s not a npm library.
