### ISSUE TITLE
The second level directory does not generate a corresponding directory list.html

### ISSUE THREAD

**Issue by Charles-one** [nanxiaobei/hugo-paper#82]
二级目录时, 第2级目录没有生成对应list.html
The second level directory does not generate a corresponding directory list.html
mkdir -p content/blog/docker 
hugo server --theme=paper
visit localhost:1313/blog/docker
预期显示docker文件下的文档list
实际没有显示

**Comment by nanxiaobei** [comment]
这是一个 Hugo 主题，不负责生成任何文件。
