### ISSUE TITLE
本地正常，Github不正常

### ISSUE THREAD

**Issue by Hambaobao** [nanxiaobei/hugo-paper#83]
你好，我在本地预览的时候一切正常，但是push到Github上以后就好像没有用到CSS样式一样了，这个会是什么原因呢？
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/48345096/107480325-5ab60e80-6bb7-11eb-901c-3aa4786b9d30.png">

**Comment by nanxiaobei** [comment]
指定 baseUrl
