### ISSUE TITLE
Posts not showing

### ISSUE THREAD

**Issue by fernandomantoan** [nanxiaobei/hugo-paper#89]
I was trying to upgrade my blog to the newest hugo-paper and hugo versions (0.82.0) and something weird happened, the front page stopped showing my blog posts. I then tried following the hugo quick start tutorial and adding paper as the theme to check if maybe I was missing something and the same behavior happened when I activated paper:

<img width="2032" alt="Screen Shot 2021-03-30 at 15 53 26" src="https://user-images.githubusercontent.com/210359/113041203-12a37900-9170-11eb-89f0-224118cb275a.png">

The structure is identical to the one in the quick start article, just one blog post and a simple configuration file as follows:

```
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "paper"
```

<img width="298" alt="Screen Shot 2021-03-30 at 15 54 56" src="https://user-images.githubusercontent.com/210359/113041384-47afcb80-9170-11eb-875a-fc194f1b346d.png">

I activated another theme to check and the posts appeared:

<img width="2032" alt="Screen Shot 2021-03-30 at 15 55 59" src="https://user-images.githubusercontent.com/210359/113041510-6dd56b80-9170-11eb-8c77-06fe4a2d4cb2.png">

Is there anything that I'm missing? Or is it related to hugo's version 0.82.0?

**Comment by nanxiaobei** [comment]
Try this directory structure: https://github.com/gohugoio/hugoBasicExample/tree/master/content, `hugo-paper` is based on that.

Try `post` folder, not `posts`.

**Comment by fernandomantoan** [comment]
After adding an empty `_index.md` file it seems to have worked:

<img width="1552" alt="Screen Shot 2021-03-31 at 10 34 48" src="https://user-images.githubusercontent.com/210359/113152654-b80c2a80-920c-11eb-9296-9a70783ac574.png">

<img width="293" alt="Screen Shot 2021-03-31 at 10 35 10" src="https://user-images.githubusercontent.com/210359/113152720-c65a4680-920c-11eb-826a-0ab5e8b7d5a8.png">
