### ISSUE TITLE
What have you done 🙀

### ISSUE THREAD

**Issue by donnydark0** [nanxiaobei/hugo-paper#95]
Can I find a backup of version 4.9 somewhere? I browsed through version history, but it keeps downloading 5.1

**Comment by nanxiaobei** [comment]
hahaha, sorry... to back to `4.9`,

You can `cd` the theme dir, e.g. `cd ./themes/paper`,

then run command `git reset --hard 8ef7ae81bab916ab046543c4ba45b86f00f05e9e`,

and it'll be `4.9` release.

> [`8ef7ae81bab916ab046543c4ba45b86f00f05e9e`](https://github.com/nanxiaobei/hugo-paper/commit/8ef7ae81bab916ab046543c4ba45b86f00f05e9e) is the a hash of release `4.9`
