### ISSUE TITLE
RSS Feed Mine Type Incorrect

### ISSUE THREAD

**Issue by WillGreen** [nanxiaobei/hugo-paper#96]
Hello,

I recently started using Hugo Paper and enjoy the theme very much.

I've found a small issue with the mime-type encoding for RSS feeds. 
Paper encodes the "+" as an entity, which breaks some RSS readers.

```
type="application/rss&#43;xml"
```

I believe this should be:

```
type="application/rss+xml"
```

I'm using the latest version of Hugo Paper (c1fe22e) and hugo v0.88.1+extended.

**Comment by nanxiaobei** [comment]
It's generated by default.
https://github.com/nanxiaobei/hugo-paper/blob/main/layouts/partials/head.html#L49~L57
