### ISSUE TITLE
Missing Tags and Categories Pages

### ISSUE THREAD

**Issue by chris-short** [nanxiaobei/hugo-paper#98]
The /tags and /categories pages are completely empty. [https://preview.devopsish.com/tags/](https://preview.devopsish.com/tags/) and [https://preview.devopsish.com/categories/](https://preview.devopsish.com/categories/) show empty pages.

Is there a workaround? This is a deal breaker for this theme.

**Comment by nanxiaobei** [comment]
Thanks but I don't have enough time to add more features, and PR welcome.
